# -*- coding: utf-8 -*-
"""preprocess.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ALXjX0tcKRkSZ7hcgljHfsyhbytE7unu
"""

import pandas as pd

def carregar_dados(path):
    return pd.read_csv(path)

def pre_processar(df):
  df.rename(columns={
    'Diabetes_012': 'diabetes',
    'HighBP': 'pressao_alta',
    'HighChol': 'colesterol_alto',
    'BMI': 'imc',
    'PhysActivity': 'atividade_fisica',
    'Smoker': 'fumante',
    'Stroke': 'avc',
    'HeartDiseaseorAttack': 'ataque_cardiaco',
    'Fruits': 'frutas',
    'Veggies': 'vegetais',
    'HvyAlcoholConsump': 'alto_consumo_alcool',
    'AnyHealthcare': 'convenio_medico',
    'DiffWalk': 'dificuldade_subir_escadas',
    'Sex': 'sexo',
    'Age': 'idade',
    }, inplace=True)

    # excluir colunas
    colunas_excluir = ["CholCheck","NoDocbcCost","GenHlth","MentHlth","PhysHlth","Education","Income"]
    df = df.drop(columns=[c for c in colunas_excluir if c in df.columns])

    # faixa etária
    depara = {
        1: "18-24",
        2: "25-29",
        3: "30-34",
        4: "35-39",
        5: "40-44",
        6: "45-49",
        7: "50-54",
        8: "55-59",
        9: "60-64",
        10: "65-69",
        11: "70-74",
        12: "75-79",
        13: "80+"
        }

    df["faixa_etaria"] = df["Age"].map(depara)

    return df

def categorizar_imc(imc):
    if imc < 18.5:
        return "Abaixo do peso"
    elif imc < 25:
        return "Peso normal"
    elif imc < 30:
        return "Sobrepeso"
    elif imc < 35:
        return "Obesidade I"
    elif imc < 40:
        return "Obesidade II"
    else:
        return "Obesidade III"

df["faixa_imc"] = df["imc"].apply(categorizar_imc)

def salvar(df, output_path):
    df.to_csv(output_path, index=False)