# -*- coding: utf-8 -*-
"""train_model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ALXjX0tcKRkSZ7hcgljHfsyhbytE7unu
"""

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, roc_auc_score
import pandas as pd

def treinar_modelo(df):
    features = ['imc','idade','pressao_alta','colesterol_alto','atividade_fisica','fumante','ataque_cardiaco','avc', 'frutas', 'vegetais','alto_consumo_alcool', 'sexo']

    X = df[features]
    y = df["diabetes_flag"]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

    model = RandomForestClassifier(n_estimators=150, random_state=42)
    model.fit(X_train, y_train)

    pred = model.predict(X_test)
    prob = model.predict_proba(X_test)[:,1]

    print("Acurácia:", accuracy_score(y_test, pred))
    print("AUC:", roc_auc_score(y_test, prob))

    df["prob_diabetes"] = model.predict_proba(X)[:,1]

    return model, df